language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - LARAVEL_VERSION=6.*
    - LARAVEL_VERSION=7.*

matrix:
    fast_finish: true
    exclude:
        - php: 7.2
          env: LARAVEL_VERSION=7.*

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --prefer-source --no-interaction

script:
    - phpunit
